#!/usr/bin/env bash
# UnicNet first install / upgrade. Run from the compose directory.
# Secrets are never printed.
#
# Do these by hand BEFORE ./install.sh:
#   1. Fill .env.example (do not leave replace_* placeholders)
#   2. cp .env.example .env && chmod 600 .env
#   3. docker login to cr.yandex (iam or oauth), as the same user that runs compose
# Realm unicnet (groups + users) ships in keycloak-import/unicnet-realm.json.
# User passwords are generated here, not taken from the JSON.
set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

COMPOSE=(docker compose --env-file .env -f compose.yml)
SKIP_PULL=0
FORCE_RENDER=0
SKIP_UNICADMIN=0
ONLY=""

usage() {
  cat <<'EOF'
Usage: ./install.sh [options]

Raises PostgreSQL, Keycloak, Vault, then the UnicNet apps.
Does not create .env and does not log in to Yandex Container Registry.

Before this script:
  1. Edit .env.example (POSTGRES_*, KEYCLOAK_*, VAULT_JWT_SIGNING_KEY,
     UNIC_LICENSE_DATA as JWT eyJ..., ROUTER_CIDR, KEYCLOAK_PUBLIC_URL)
  2. cp .env.example .env && chmod 600 .env
  3. docker login --username iam --password-stdin cr.yandex
     or: docker login --username oauth --password-stdin cr.yandex

Realm import is already in keycloak-import/unicnet-realm.json
(groups unicnet_admin_group / unicnet_superuser_group / unicnet_user_group,
user unicadmin in all three). Passwords are generated by this script.

Then:
  ./install.sh

The script checks .env, builds vault-values.json if missing, pulls images,
starts pg/keycloak/vault, loads Vault, sets passwords for realm users,
starts the full graph, and checks Front/Backend/SysLog/Keycloak.

Options:
  --skip-pull           Do not docker compose pull
  --render-vault        Recreate vault-values.json from .env even if it exists
  --skip-unicadmin      Do not set realm user passwords
  --only=core           Only pg + keycloak + vault
  --only=vault          Only bootstrap Vault
  --only=unicadmin      Only set realm user passwords
  --only=stack          Only start the full compose graph
  --only=check          Only health checks
  -h, --help            Show this help

Generated (chmod 600, not for git):
  vault-values.json
  .keycloak-passwords
  .unicadmin-password
EOF
}

for arg in "$@"; do
  case "$arg" in
    --skip-pull) SKIP_PULL=1 ;;
    --render-vault) FORCE_RENDER=1 ;;
    --skip-unicadmin) SKIP_UNICADMIN=1 ;;
    --only=*) ONLY="${arg#--only=}" ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $arg" >&2; usage >&2; exit 1 ;;
  esac
done

need() {
  command -v "$1" >/dev/null 2>&1 || { echo "Required command not found: $1" >&2; exit 1; }
}

log() { printf '[install] %s\n' "$*"; }

wait_http() {
  local url="$1" label="$2" attempts="${3:-60}"
  local i
  for i in $(seq 1 "$attempts"); do
    if curl -fsS --max-time 5 "$url" >/dev/null 2>&1; then
      log "$label is ready"
      return 0
    fi
    sleep 2
  done
  echo "$label did not become ready: $url" >&2
  return 1
}

env_get() {
  python3 - "$1" <<'PY'
import sys
from pathlib import Path
key = sys.argv[1]
text = Path(".env").read_text(encoding="utf-8")
val = None
for raw in text.splitlines():
    line = raw.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    k, v = line.split("=", 1)
    if k.strip() != key:
        continue
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
        v = v[1:-1]
    val = v
if val is None:
    sys.exit(2)
print(val, end="")
PY
}

require_env() {
  local missing=0 key val
  for key in \
    POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD \
    KEYCLOAK_ADMIN KEYCLOAK_ADMIN_PASSWORD KEYCLOAK_PUBLIC_URL \
    VAULT_JWT_SIGNING_KEY UNIC_LICENSE_DATA ROUTER_CIDR
  do
    if ! val="$(env_get "$key" 2>/dev/null)"; then
      echo "Missing $key in .env" >&2
      missing=1
      continue
    fi
    if [[ "$val" == replace* || -z "$val" ]]; then
      echo "Fill $key in .env.example, then: cp .env.example .env && chmod 600 .env" >&2
      missing=1
    fi
  done
  if [[ "$missing" -ne 0 ]]; then
    exit 1
  fi
  local key_len lic
  key_len="$(env_get VAULT_JWT_SIGNING_KEY | wc -c)"
  if [[ "$key_len" -lt 32 ]]; then
    echo "VAULT_JWT_SIGNING_KEY must be at least 32 characters" >&2
    exit 1
  fi
  lic="$(env_get UNIC_LICENSE_DATA)"
  if [[ "$lic" != eyJ* ]] || [[ "$(grep -o '\.' <<<"$lic" | wc -l)" -lt 2 ]]; then
    echo "UNIC_LICENSE_DATA must be a JWT (starts with eyJ). Old Solid UnicLicense blobs are not accepted." >&2
    exit 1
  fi
}

render_vault_values() {
  if [[ -f vault-values.json && "$FORCE_RENDER" -ne 1 ]]; then
    log "vault-values.json already exists; leave it (use --render-vault to rebuild)"
    chmod 600 vault-values.json || true
    return 0
  fi
  test -r vault-values.example.json || { echo "vault-values.example.json is missing" >&2; exit 1; }
  python3 - <<'PY'
import json
from pathlib import Path

def load_env(path):
    env = {}
    for raw in Path(path).read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        v = v.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
            v = v[1:-1]
        env[k.strip()] = v
    return env

env = load_env(".env")
values = json.loads(Path("vault-values.example.json").read_text(encoding="utf-8"))
pg = env["POSTGRES_DB"]
user = env["POSTGRES_USER"]
password = env["POSTGRES_PASSWORD"]
kc_url = env["KEYCLOAK_PUBLIC_URL"].rstrip("/") + "/"
license_jwt = env["UNIC_LICENSE_DATA"]
license_api = env.get("API_LICENSE_URL", "https://license.unic.chat/")
cidr = env["ROUTER_CIDR"]
admin = env["KEYCLOAK_ADMIN"]
admin_password = env["KEYCLOAK_ADMIN_PASSWORD"]

def cs(app):
    return (
        f"Host=pg;Port=5432;Database={pg};Username={user};"
        f"Password={password};Application Name={app}"
    )

values["Unic.Logger"]["Storage__ConnectionString"] = cs("Unic.Logger")
values["UnicNet.SysLog"]["Storage__ConnectionString"] = cs("UnicNet.SysLog")
values["UnicNet.Backend"]["Storage__ConnectionString"] = cs("UnicNet.Backend")
values["UnicNet.Router"]["Router__Keycloak__Url"] = kc_url
values["UnicNet.Router"]["Router__Keycloak__Admin__Username"] = admin
values["UnicNet.Router"]["Router__Keycloak__Admin__Password"] = admin_password
values["UnicNet.Router"]["Router__Cidr"] = cidr
values["UnicNet.Router"]["Router__License__Data"] = license_jwt
values["UnicNet.Router"]["UniCommLicenseData"] = license_jwt
values["UnicNet.Backend"]["Keycloak__Url"] = kc_url
values["UnicNet.Backend"]["Keycloak__Admin__Username"] = admin
values["UnicNet.Backend"]["Keycloak__Admin__Password"] = admin_password
values["UnicNet.Backend"]["UniCommLicenseData"] = license_jwt
values["UNFrontV2"]["UniCommLicenseData"] = license_jwt
values["UNFrontV2"]["Api_License_Url"] = license_api

out = Path("vault-values.json")
out.write_text(json.dumps(values, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
out.chmod(0o600)
print("wrote vault-values.json")
PY
}

set_unicadmin() {
  python3 - <<'PY'
import json, pathlib, secrets, string, sys, time, urllib.parse, urllib.request

kc = "http://127.0.0.1:8095"
realm = "unicnet"
realm_file = pathlib.Path("keycloak-import/unicnet-realm.json")
pass_file = pathlib.Path(".keycloak-passwords")
unicadmin_file = pathlib.Path(".unicadmin-password")
alphabet = string.ascii_letters + string.digits

def load_env(path):
    env = {}
    for raw in pathlib.Path(path).read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        v = v.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
            v = v[1:-1]
        env[k.strip()] = v
    return env

def req(method, url, data=None, headers=None, timeout=20):
    body = None
    hdrs = dict(headers or {})
    if data is not None and not isinstance(data, (bytes, bytearray)):
        body = json.dumps(data).encode()
        hdrs.setdefault("Content-Type", "application/json")
    elif isinstance(data, (bytes, bytearray)):
        body = data
    request = urllib.request.Request(url, data=body, headers=hdrs, method=method)
    try:
        with urllib.request.urlopen(request, timeout=timeout) as resp:
            return resp.status, resp.read()
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read()

def load_passwords(path):
    out = {}
    if not path.exists():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        user, password = line.split("=", 1)
        if user and password:
            out[user] = password
    return out

def save_passwords(path, mapping):
    lines = [f"{user}={mapping[user]}" for user in sorted(mapping)]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o600)

if not realm_file.is_file():
    raise SystemExit("Missing keycloak-import/unicnet-realm.json (ships with the kit)")

wanted_users = json.loads(realm_file.read_text(encoding="utf-8")).get("users") or []
if not wanted_users:
    raise SystemExit("unicnet-realm.json has no users")

env = load_env(".env")
admin_user = env["KEYCLOAK_ADMIN"]
admin_pass = env["KEYCLOAK_ADMIN_PASSWORD"]

token = None
for _ in range(30):
    form = urllib.parse.urlencode({
        "client_id": "admin-cli",
        "grant_type": "password",
        "username": admin_user,
        "password": admin_pass,
    }).encode()
    st, raw = req(
        "POST",
        f"{kc}/realms/master/protocol/openid-connect/token",
        data=form,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    if st == 200:
        token = json.loads(raw)["access_token"]
        break
    time.sleep(2)
if not token:
    raise SystemExit("Cannot get Keycloak master token. Is Keycloak up and KEYCLOAK_ADMIN correct?")

auth = {"Authorization": f"Bearer {token}"}
st, raw = req("GET", f"{kc}/admin/realms/{realm}/groups", headers=auth)
if st != 200:
    raise SystemExit(f"Cannot list groups: HTTP {st}")
groups = {g["name"]: g["id"] for g in json.loads(raw)}

passwords = load_passwords(pass_file)
if unicadmin_file.exists() and unicadmin_file.stat().st_size > 0:
    passwords.setdefault("unicadmin", unicadmin_file.read_text().strip())

for spec in wanted_users:
    username = spec.get("username")
    if not username:
        continue
    st, raw = req(
        "GET",
        f"{kc}/admin/realms/{realm}/users?username={urllib.parse.quote(username)}&exact=true",
        headers=auth,
    )
    if st != 200:
        raise SystemExit(f"Cannot list users: HTTP {st}")
    found = json.loads(raw)
    if not found:
        payload = {
            "username": username,
            "email": spec.get("email") or f"{username}@local.com",
            "firstName": spec.get("firstName") or username,
            "lastName": spec.get("lastName") or "UnicNet",
            "enabled": spec.get("enabled", True),
            "emailVerified": spec.get("emailVerified", True),
        }
        st, raw = req("POST", f"{kc}/admin/realms/{realm}/users", data=payload, headers=auth)
        if st not in (201, 204):
            raise SystemExit(f"Cannot create {username}: HTTP {st} {raw[:200]!r}")
        st, raw = req(
            "GET",
            f"{kc}/admin/realms/{realm}/users?username={urllib.parse.quote(username)}&exact=true",
            headers=auth,
        )
        found = json.loads(raw)
    user_id = found[0]["id"]

    password = passwords.get(username)
    if not password:
        password = "".join(secrets.choice(alphabet) for _ in range(20))
        passwords[username] = password

    st, raw = req(
        "PUT",
        f"{kc}/admin/realms/{realm}/users/{user_id}/reset-password",
        data={"type": "password", "value": password, "temporary": False},
        headers=auth,
    )
    if st not in (204, 200):
        raise SystemExit(f"Cannot set password for {username}: HTTP {st} {raw[:200]!r}")

    needed = []
    for path in spec.get("groups") or []:
        name = path.strip("/").split("/")[-1]
        if name:
            needed.append(name)
    st, raw = req("GET", f"{kc}/admin/realms/{realm}/users/{user_id}/groups", headers=auth)
    have = {g["name"] for g in json.loads(raw)} if st == 200 else set()
    for name in needed:
        gid = groups.get(name)
        if not gid:
            print(f"warning: group {name} is missing in realm", file=sys.stderr)
            continue
        if name in have:
            continue
        st, raw = req("PUT", f"{kc}/admin/realms/{realm}/users/{user_id}/groups/{gid}", headers=auth)
        if st not in (204, 200):
            raise SystemExit(f"Cannot join {username} to {name}: HTTP {st}")

save_passwords(pass_file, passwords)
if "unicadmin" in passwords:
    unicadmin_file.write_text(passwords["unicadmin"] + "\n", encoding="utf-8")
    unicadmin_file.chmod(0o600)
    form = urllib.parse.urlencode({
        "client_id": "FrontUiV2",
        "grant_type": "password",
        "username": "unicadmin",
        "password": passwords["unicadmin"],
        "scope": "openid",
    }).encode()
    st, raw = req(
        "POST",
        f"{kc}/realms/{realm}/protocol/openid-connect/token",
        data=form,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    if st != 200:
        raise SystemExit(f"unicadmin password grant failed: HTTP {st}")

print(f"realm user passwords are in {pass_file} (not printed)")
PY
}

phase_prep() {
  need docker
  need curl
  need jq
  need python3
  docker compose version >/dev/null
  test -f compose.yml
  test -f .env.example
  if [[ ! -f .env ]]; then
    cat >&2 <<'EOF'
No .env. Fill .env.example first, then copy it:

  # edit .env.example
  cp .env.example .env
  chmod 600 .env

Then rerun ./install.sh.
EOF
    exit 1
  fi
  test -f keycloak-import/unicnet-realm.json || {
    echo "Missing keycloak-import/unicnet-realm.json (ships with the kit)" >&2
    exit 1
  }
  require_env
  render_vault_values
  chmod +x bootstrap-vault.sh
}

phase_pull() {
  if [[ "$SKIP_PULL" -eq 1 ]]; then
    log "skip pull"
    return 0
  fi
  log "pulling images (registry login must already be done by hand)"
  "${COMPOSE[@]}" pull
}

phase_core() {
  log "starting pg, keycloak, vault"
  "${COMPOSE[@]}" up -d pg keycloak vault
  wait_http "http://127.0.0.1:8200/openapi/v1.json" "Vault"
  wait_http "http://127.0.0.1:8095/realms/unicnet/.well-known/openid-configuration" "Keycloak realm unicnet" 90
}

phase_vault() {
  log "loading secrets into Vault"
  ./bootstrap-vault.sh vault-values.json
}

phase_stack() {
  log "starting full graph"
  "${COMPOSE[@]}" up -d --wait
}

phase_check() {
  log "health checks"
  curl -fsS -o /dev/null http://127.0.0.1:8080/
  curl -fsS -o /dev/null http://127.0.0.1:30111/health/ready
  curl -fsS -o /dev/null http://127.0.0.1:8001/health/live
  curl -fsS -o /dev/null http://127.0.0.1:8095/realms/unicnet/.well-known/openid-configuration
  "${COMPOSE[@]}" ps
  local front_lic
  front_lic="$(docker exec unicnet-frontend-1 printenv UniCommLicenseData 2>/dev/null | head -c 3 || true)"
  if [[ "$front_lic" != eyJ ]]; then
    echo "Frontend is missing UniCommLicenseData env" >&2
    exit 1
  fi
  log "OK. UI http://$(hostname -I | awk '{print $1}'):8080/  user unicadmin, passwords in .keycloak-passwords"
  log "Do not curl http://127.0.0.1:30115/health/ready — Router HTTP health resets the WSS tunnel."
}

case "$ONLY" in
  "")
    phase_prep
    phase_pull
    phase_core
    phase_vault
    if [[ "$SKIP_UNICADMIN" -eq 0 ]]; then
      set_unicadmin
    fi
    phase_stack
    phase_check
    ;;
  core) phase_prep; phase_core ;;
  vault) phase_prep; phase_vault ;;
  unicadmin) phase_prep; set_unicadmin ;;
  stack) phase_prep; phase_stack ;;
  check) phase_check ;;
  *) echo "Unknown --only=$ONLY" >&2; exit 1 ;;
esac
